<!DOCTYPE html><html lang='en'><head><title>[except.uncaught]</title><meta charset='UTF-8'/><link rel='stylesheet' type='text/css' href='14882.css'/><link rel='stylesheet' type='text/css' href='expanded.css' title='Notes and examples expanded'/><link rel='alternate stylesheet' type='text/css' href='colored.css' title='Notes and examples colored'/><link rel='alternate stylesheet' type='text/css' href='collapsed.css' title='Notes and examples collapsed'/><link rel='icon' href='icon.png'/></head><body><div class='wrapper'><h1 ><a class='secnum' style='min-width:73pt'>13</a> Exception handling <a class='abbr_ref' href='./#except'>[except]</a></h1><h2 ><a class='secnum' style='min-width:88pt'>13.5</a> Special functions <a class='abbr_ref' href='except.special#except.uncaught'>[except.special]</a></h2><h3 ><a class='secnum' style='min-width:103pt'>13.5.2</a> The <span class='texttt'>std&#x200b;::&#x200b;uncaught_&shy;exceptions()</span> function <a class='abbr_ref'>[except.uncaught]</a></h3><span class='indexparent'><a class='index' id='lib:uncaught_exceptions'></a></span><div class='para' id='1'><div class='marginalizedparent'><a class='marginalized' href='#1'>1</a></div><div class='sourceLinkParent'><a class='sourceLink' href='https://github.com/cplusplus/draft/tree/be83c0b472b3912df2ba63bb2831f2a7798badd3/source/exceptions.tex#L1106'>#</a></div><div id='1.sentence-1' class='sentence'>An exception is considered uncaught
after completing the initialization of the <a href='except.throw#def:exception_handling,exception_object'>exception object</a>
until completing the activation of a handler for the exception (<a href='except.handle'>[except.handle]</a>)<a class='hidden_link' href='#1.sentence-1'>.</a></div> <div id='1.sentence-2' class='sentence'>This includes stack unwinding<a class='hidden_link' href='#1.sentence-2'>.</a></div> <div id='1.sentence-3' class='sentence'>If an exception is rethrown (<a href='expr.throw'>[expr.throw]</a>, <a href='propagation'>[propagation]</a>),
it is considered uncaught from the point of rethrow
until the rethrown exception is caught<a class='hidden_link' href='#1.sentence-3'>.</a></div> <div id='1.sentence-4' class='sentence'>The function <a href='uncaught.exceptions'><span class='texttt'>std&#x200b;::&#x200b;uncaught_&shy;exceptions()</span></a>
returns the number of uncaught exceptions in the current thread<a class='hidden_link' href='#1.sentence-4'>.</a></div> </div></div></body></html>