<!DOCTYPE html><html lang='en'><head><title>[except.uncaught]</title><meta charset='UTF-8'/><link rel='stylesheet' type='text/css' href='14882.css'/><link rel='icon' href='icon.png'/></head><body><div class='wrapper'><h1 ><a class='secnum' style='min-width:73pt'>18</a> Exception handling <a class='abbr_ref' href='./#except'>[except]</a></h1><h2 ><a class='secnum' style='min-width:88pt'>18.5</a> Special functions <a class='abbr_ref' href='except.special#except.uncaught'>[except.special]</a></h2><h3 ><a class='secnum' style='min-width:103pt'>18.5.2</a> The <span class='texttt'>std&#x200b;::&#x200b;uncaught_&shy;exceptions()</span> function <a class='abbr_ref'>[except.uncaught]</a></h3><p ><span class='indexparent'><a class='index' id='lib:uncaught_exceptions'></a></span></p><div class='para' id='1'><div class='marginalizedparent'><a class='marginalized' href='#1'>1</a></div><div class='sourceLinkParent'><a class='sourceLink' href='https://github.com/cplusplus/draft/tree/e8e0fc6c0ec75b6ea4bbdc0134251bbc60870e25/source/exceptions.tex#L1088'>#</a></div><p >An exception is considered uncaught
after completing the initialization of the <a href='except.throw#def:exception_handling,exception_object'>exception object</a>
until completing the activation of a handler for the exception (<a href='except.handle'>[except.handle]</a>).
This includes stack unwinding.
If an exception is rethrown (<a href='expr.throw'>[expr.throw]</a>, <a href='propagation'>[propagation]</a>),
it is considered uncaught from the point of rethrow
until the rethrown exception is caught.
The function <a href='uncaught.exceptions'><span class='texttt'>std&#x200b;::&#x200b;uncaught_&shy;exceptions()</span></a>
returns the number of uncaught exceptions in the current thread.
</p></div></div></body></html>